### ISSUE TITLE
ADCIRC tag noaa.stofs.2d.glo.v1.1.0r2 does not build with gfortran

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#1046]
Appears to be due to mismatched if/endif as in #548 and #819

**Comment by jasonfleming** [comment]
related work with #1037

**Comment by wwlwpd** [comment]
At this time, I will have to support gfortran as a different patchset. So less of a bug and more of a _missing_ thing..

**Comment by wwlwpd** [comment]
Or maybe I can clean up the exsting..will have to look.

**Comment by wwlwpd** [comment]
I can take care of this and #1048 at the same time.

**Comment by wwlwpd** [comment]
@jasonfleming can you quantify the importance of supporting `gfortran` via `build adcirc` ?

**Comment by jasonfleming** [comment]
The issue here is super small, just a mismatched if/endif that doesn't affect intel support. If it was not fixed with the earlier work on #1048 then I can fix it.

**Comment by wwlwpd** [comment]
If you don't mind that would clarify the need. I bring up ubuntu/alpine (& docker) because `build adcirc` will set `compiler=gfortran` only if ASGS is initially set up with fortran (not intel). I can try to do that on HPC (e.g., super mike) if you think that would be useful. Otherwise, I tend to equate a non-intel/non-commercial compiler environment to be a private linux of some kind. What do you think?

**Comment by jasonfleming** [comment]
I agree 100%: we only use gfortran on non-HPC environments. We don't need to support gfortran as an alternative to intel on any HPC.

**Comment by wwlwpd** [comment]
This will be solved in #1037 (working in principle, testing on other platforms).

**Comment by wwlwpd** [comment]
I just tested this on ubuntu (non-docker) and it's compiling after #1037. Closing.
