### ISSUE TITLE
`HottifySWAN` v55.01 failed to build with `gfortran`

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#1067]
The only issue here is that the `macros.inc` file was set to use `ifort` rather than `gfortran` ... I then did `mv macros.inc.gfortran macros.inc` and then re-executed the shell script to build the code and everything worked without issue. So this is only related to having the right `macros.inc` in there.

**Comment by wwlwpd** [comment]
This might be related to #1046, I noticed some oddness with >55.01(when `./swan` was moved to `./thirdparty/swan` upstream) and the patchsets related to the `swan` directory versus `thirdparty/swan` directory; I may have messed up and applied some <55.01 patches to these. I'll bite the bullet very soon to just get all this back into order, including consoladating the "patchset glut" in #1037.

**Comment by wwlwpd** [comment]
@jasonfleming I wanted to put this note somewhere. But it's important to note that ASGS can be installed supporting either _intel_ or _gfortran_ - the biggest difference, and really intention of this, is in terms of: _what compiler do you intend to use when compiling ADCIRC_?

This is the essential factor, because it affects with what compiler _netCDF_ and it's underlying dependency, _HDF5_ are compiled.

That doesn't mean a patchset can support only _intel_ or only _gfortran_ - but it could be in some cases that compiler support will be mutually exclusive. I think we should strive for patchsets working for either. This information is passed to the ADCIRC compiler phase so the work to ensure this will be the state of `work/cmplrflags.mk`.

**Comment by jasonfleming** [comment]
I think I understand what you are saying. We want to use intel compilers on platforms where they are available and gcc/gfortran everywhere else. And everything should build correctly in either case, without changing the content of the patches that are applied. Is that right?

**Comment by wwlwpd** [comment]
Mostly, the additional point is we should be able to install ASGS anywhere by selecting `gfortran` during `init-asgs.sh` and have it all work.

**Comment by wwlwpd** [comment]
This will be getting solved in #1037 (testing on other platforms now)
