### ISSUE TITLE
create VirtualBox "appliance" for direct import

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#1135]
~~Can vagrant be used here?~~ Yes and it's a good idea ...

- [x] deprecate "vagrant" type and add "oracle linux 8"
- [x] create `Vagrantfile` that adds build essentials, gfortran, etc
- [x] `scratch` is sync'd (shared) folder to host system
- [x] `work` is sync'd (shared) folder to host system
- [ ] init `~/asgs-global.conf`   (with default email creds)
- [ ] init `~/.ssh/id_rsa[.pub]`  (with proper permissions)
- [ ] init `~/.ssh/config`

Reference Links:

- https://yum.oracle.com/boxes/
- https://github.com/oracle/vagrant-projects
- https://yum.oracle.com/oracle-linux-isos.html
- https://www.oracle.com/downloads/developer-vm/community-downloads.html

**Comment by wwlwpd** [comment]
@jasonfleming - notable, Oracle Linux tracks Redhat Enterprise which is usually what we find on the "institutional" HPC clusters (as opposed to debian/ubuntu derivatives).

**Comment by wwlwpd** [comment]
* sudo yum groupinstall 'Development Tools'
* sudo yum install gcc-fortran

**Comment by wwlwpd** [comment]
![image](https://github.com/StormSurgeLive/asgs/assets/46434714/af9ad933-3a40-4802-8551-b70afdcb0fc0)

**Comment by jasonfleming** [comment]
Very cool. I did not know that about RHEL and Oracle Linux. I was a fan of Red Hat back in the day but have not used it since early 2000s when they started focusing exclusively on RHEL (I switched to straight debian). Happy to check it out and switch back if it is indicated. Looking forward to taking the vagrant implementation for a spin!
