### ISSUE TITLE
investigate improvements to bash scripts through pipefail options

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#163]
Basically, "use strict" equivalent for bash scripts.

https://coderwall.com/p/fkfaqq/safer-bash-scripts-with-set-euxo-pipefail
https://gist.github.com/adoyle-h/4cfc93760d1cddf41db9e3bf4f401dc8

For example, 

    set -euxo pipefail
    shopt -s inherit_errexit

**Comment by jasonfleming** [comment]
Hey @wwlwpd I had a look at the page and it looks like a great idea that could solve a lot of hard-to-debug issues that we've struggled with, especially for new Operators. 

However, in our HA environment, `set -e` makes me a little nervous. For asgs_main.sh in particular, we want to have code in the script that will detect errors and recover from them if possible, rather than exiting the script immediately. My hope for asgs_main.sh is that it never exits voluntarily, it always has to be explicitly killed internally. But in any case I agree that this is the direction we want to go, we just need to ease into it over time and build experiences.  

Also, it would be great to provide your link in the comments around `set -euxo` and even cut and paste the meaning of these options into the comments. They are pretty neat options and probably not commonly used.

**Comment by jasonfleming** [comment]
I wonder if it would make sense to use `set -e` in all our bash scripts for dev and test and disable for production? Also maybe pair this with an exit trap that will report good useful error messages?

**Comment by wwlwpd** [comment]
Sounds like you've considered this before and found it to not be a good fit. I'm not in any rush to change things. I am going to change the name of the issue to be something less definative.

**Comment by jasonfleming** [comment]
No I have not seen `set -e` before but I like it ... however yes we have run into issues with overly fatal responses to recoverable conditions (or at least conditions that are Operator-correctable for the next advisory). This `set -e` is a good idea that can also help us build better error handling and recovery into the code.

**Comment by wwlwpd** [comment]
closing, may eventually arrive to this being a _thing_ during our she cleanups, but not here
