### ISSUE TITLE
advisory time for RMQ not getting set when `TROPICALCYCLONE=on`

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#515]
@BrianOBlanton I need the error you mentioned recorded with some minimal amount of detail (e.g., general issue, how reproduce, etc). Thanks!

**Comment by BrianOBlanton** [comment]
So I can update this issue.  Last night, I used git blame and it indicated that I accidentally deleted the line that sets RMQADVISORY.   that has been restored, and the messaging/advisory info is back to normal.  Sorry for the false alarm.
 
I was about to slack you about this (that the issue is resolved) when I saw the github email.  So this can be closed.

**Comment by wwlwpd** [comment]
Great you figured it out. I do these kind of things all the time.
