### ISSUE TITLE
question about assigning post-processing tasks to individual ASGS operators

### ISSUE THREAD

**Issue by carolakaiser** [StormSurgeLive/asgs#600]
ASGS is not only operated by several operators who represent unique organizations and/or data interests but also have data consumers that require different sets of ASGS output results. One example is the wind 10m layer that is not needed by RENCI but valuable for the CERA Group.
Is ASGS currently configured in a similar way for the shell scripts that deal with creating Opendap lists or transmit any data (in that specific case the transmit_rps.sh script)? The more specific question is: are these post-processing tasks a global configuration in the ASGS config files or can they be set individually by each operator? 
Thanks :-)

**Comment by wwlwpd** [comment]
this is a question for @jasonfleming

**Comment by jasonfleming** [comment]
Hello @carolakaiser the ASGS executes post processing scripts as specified by the Operators in their individual configuration files. These are stored in a simple bash array which is empty by default. So the ASGS does not do any post processing by default. It only post processes using the scripts that the Operators specify in their own config files. 

As an aside, the Wind10m layer data are produced as a separate scenario. The `includeWind10m.sh` post processing script just creates symlinks to the resulting output files within the corresponding full physics scenario so that they can be posted to opendap together (if that post processing script has been specified by the Operator).

If the Operator selects the `transmit_rps.sh` script in their config file, the ASGS will run that when the associated scenario finishes. If not, then `transmit_rps.sh` will not run.

**Comment by carolakaiser** [comment]
Thank you.
Let's assume we are in the middle of a hurricane. The config files are then heavily distributed and shared through the scenario package. Does that mean that an individual operator needs to edit those config files every time before using them if they want to have different options than the main operator (@jasonfleming)?

**Comment by carolakaiser** [comment]
Thank you for clarifying those questions during a meeting. Please close the ticket if you would like to.
