### ISSUE TITLE
`asgs-lint` command/script - startup health check and configuration echo at start of ASGS

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#756]
When the ASGS starts, it performs a limited health check. It does not check allocation status for example. The combination of the existing ASGS startup tests and the `verify` checks from `asgsh` could be used right at the start of an ASGS startup to catch issues prior to execution. This could even be done as a dry run, to check configuration, existence of files, availability of allocation, etc.

**Comment by wwlwpd** [comment]
What would be a good first pass of checks? And are there checks that should happen on start but not on subsequent iterations; or not at first or after subsequent iterations?

**Comment by jasonfleming** [comment]
When the ASGS first starts, it checks to make sure the ADCIRC executables are actually there, it checks to see if the mesh file and control template are there, etc. It mainly uses checkFileExistence() and checkDirExistence(). A good first step would be to extract the code that runs these checks so that an Operator can run the checks without actually starting up ASGS. This would provide a dry run smoke test. There are other sanity checks in the code that catch conflicts in configuration parameters that we could extract later. These same test could all be run at regular intervals

**Comment by wwlwpd** [comment]
Sounds good

**Comment by wwlwpd** [comment]
I am working on an approach that looks at the configuration file statically and it will be structured such that we can order checks on priority - "will fail", "not fatal but should be fixed", etc. So it'll be easy to add stuff as we find things we want to check for.

Anything we do as a "during flight" check will be structured similarly, but will be a different script most likely.

**Comment by wwlwpd** [comment]
@jasonfleming - please take a look at #779 to see where I am going with `asgs-lint`; then we can discuss the challenges we might face here and the right approach. For example, for now the "lint" script is "static" meaning it doesn't actually run or _source_ `$ASGS_CONFIG` - and I think that this is the correct approach since the config file itself has at least a couple of other files that it then will `source`.

But it's also not hard to statically check using `grep`, or if it gets too hairy, `perl`, for things we've learned over time will really tend to bite us. If we end up having to do more complicated checks, then we might have to rethink this approach.

**Comment by wwlwpd** [comment]
Will add checking ENV/$ASGS_CONFIG for:

-     `CYCLETIMELIMIT`
-     `PPN`
-     superficial math check on `NCPU`, `NCPUCAPACITY`, and `NUMWRITERS`
