### ISSUE TITLE
perl install error on new platform

### ISSUE THREAD

**Issue by BrianOBlanton** [StormSurgeLive/asgs#766]
I'm installing asgs on a new platform, with completely clean user environment, no modules installed, etc.    error message below.

==> Found dependencies: Params::Validate, DateTime::Format::Strptime
--> Working on Params::Validate
Fetching http://www.cpan.org/authors/id/D/DR/DROLSKY/Params-Validate-1.30.tar.gz ... OK
Configuring Params-Validate-1.30 ... OK
Building and testing Params-Validate-1.30 ... FAIL
! Installing Params::Validate failed. See /home/bblanton/opt/default/perl5/.cpanm/work/1647364444.30936/build.log for details. Retry with --force to force install it.
--> Working on DateTime::Format::Strptime
Fetching http://www.cpan.org/authors/id/D/DR/DROLSKY/DateTime-Format-Strptime-1.79.tar.gz ... OK
Configuring DateTime-Format-Strptime-1.79 ... OK
Building and testing DateTime-Format-Strptime-1.79 ... OK
Successfully installed DateTime-Format-Strptime-1.79
! Installing the dependencies failed: Module 'Params::Validate' is not installed
! Bailing out the installation for DateTime-Format-Builder-0.83.
1 distribution installed
command for "Step for installing, adding, and updating required Perl modules" exited with an error code of 1, stopping. Please fix and rerun.

**Comment by wwlwpd** [comment]
Thanks @BrianOBlanton - any chance I can get on this platform to "port" ASGS? Generally speaking, this is how getting started on a new platform is handled.

**Comment by BrianOBlanton** [comment]
yes, I'll set that up tonight.  It's on Penguin.

**Comment by wwlwpd** [comment]
Ok, thank you - I think I tried to get going on Penguin once but discontinued the effort due to lack of access. I think that the way they do it might require some playing around since I understand that they use a private VM as the "head node". Anyway, I'd classify this kind of "topology" as a new one that needs to be investigated. I am sure that it won't be too hard to get it going on there, though.

**Comment by BrianOBlanton** [comment]
@wwlwpd Your Penguin act has been reactivated.  Did you get an email from Penguin?

**Comment by wwlwpd** [comment]
@BrianOBlanton this was mostly resolved with #790 but there is an issue that I recently discovered with the "new" platform system that will be getting resolved in #811. So once that merges,  you should be good to go on penguin.

**Comment by wwlwpd** [comment]
Closing, please re-open or create a new issue if any new problems are found.

**Comment by notstarboard** [comment]
I'm running into this same error while trying to set up an ASGS instance on Hatteras (trying to set up a backup instance there for RICHAMP in case Unity ever has trouble). The only slight difference is that it's now Params-Validate-1.31 failing instead of 1.30. File-Map-0.71 also fails to build, but the Params-Validate-1.31 is the last thing that gets sent to stdout before init-asgs.sh exits.

**Comment by wwlwpd** [comment]
IIRC, this was because Rostam's`/tmp` is very small and fills up. It could also be your `$HOME`. You can set the temporary directory,

```
TMPDIR=/path/to/tmp/dir ./init-asgs.sh
```

Otherwise, it defaults to `$ASGS_HOME`, which unless changed defaults to `$HOME`:

https://github.com/StormSurgeLive/asgs/blob/master/init-asgs.sh

**Comment by notstarboard** [comment]
Thanks for the suggestion! Running with a different TMPDIR and --force got me past this error. Currently I'm hitting the same error from #1119; just starting to look into it more. I think we can close this issue again, though!
