### ISSUE TITLE
templatize or standardize `NSCREEN` value in all fort.15 in supported meshes

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#780]
@jasonfleming - it'd be supremely helpful if we standardized this to be a reasonable negative number, so it generated reliably an `adcirc.log` (per ADCIRC documentation) that provides stepwise output the current model situation - I've ALWAYS found this output valuable, though I just now realized if <0 it'll write to a `adcirc.log`.

You can see the spread of values (but not the actual distribution) with, 

```
find ./input/meshes -type f | xargs grep -h NSCREEN | awk '{print $1}' | sort -nr | uniq
```

It's all over the place,

```
2000
1000
600
100
1
-1
-100
-1000
-2000
```
For this issue, I'd like to see what you thought about me standardizing on, say `-10` as a template variable default? I'd update all the fort.15s in all the meshes currently supported.

As future work, it would pretty simple to design some "monitoring" that can check this file by parsing the latest line and also maybe by tracking how often it is completing "10" timesteps for a fairly good sample  to compute module throughput (e.g., X ts/minute). The output line also has other valuable information, as you know, timestep, min/max values for elevation and velocities as well as "%" complete (wrt to total `RNDAY`, `DT`, and current timestep). But we can't do anything reliably if `NSCREEN` is inconsistently applied everywhere.

This would also help greatly with debugging and questions like, _is it really running?_

**Comment by jasonfleming** [comment]
Hey @wwlwpd this standardization sounds great, I'd like to make this `%NSCREEN%` in all the fort.15 templates so we can configure dynamically this via ASGS. (Eventually, I'd like for every parameter in the fort.15 template to be controllable via ASGS.) 

The original reason for making it possible to write this output to `adcirc.log` was that some HPC platforms have hopelessly and unreasonably slow i/o to stdout, which is where it would go otherwise. In any case, output to `adcirc.log` will be buffered, so -10 might not be more granular than -1000 (which is what I usually use) in terms of how often it is updated. But once it becomes a template variable, we can make it anything we want. 

In terms of being able to tell if it is really running, and measure throughput, I use the `scenario.status.json` file, which counts the number of datasets in the output files. But that doesn't tell you if the model is going unstable, etc.

**Comment by jasonfleming** [comment]
I am happy to make this change, but don't want to duplicate it if you are working on it. Let me know. :-)

**Comment by wwlwpd** [comment]
Great. I'll do it today or tomorrow - I want to get into the template stuff anyway. I think this will open up a nice view to things if/when we need to use it by setting this variable.

And if we're going to fully template a `fort.15`, then I think what we should do is basically create a master `fort.15` using `Template::Toolkit` (since it is fully dynamic and programmable). From there, we can basically craft the right hash structure to send it for each run we want; and this will give us really nice control over `fort.15` - fully extracting it as I think you're envisioning. Let's discuss this soon because I thing doing a general `fort.15` template is something either of us can do, but I wanted to talk to you about `Template::Toolkit` first (and its many features).

Also if we do it right, embedding the "rendering" logic into the template with GREATLY simplify the `control_file_gen.pl` - likely to the point where we should just write a new one. And once we do this, we'll have a really good idea of how to apply the same approach to generating queue scripts - again, likely making it possible to just create a new, much more simplified `qscript.pl`.
